### ISSUE TITLE
Unable to install due to encoding error

### ISSUE THREAD

**Issue by MsLimon** [schlegelp/pyfim#1]
I was unable to install the package because of the following error: 

"_ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-fbtj6z7y/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-fbtj6z7y/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-req-build-fbtj6z7y/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-fbtj6z7y/setup.py", line 21, in <module>
        long_description=open('README.md').read(),
      File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 806: ordinal not in range(128)_"

I was able to fix it by downloading the source and changing the following line of the setup.py:
`long_description=open('README.md').read(),`
by:
`long_description=codecs.open('README.md',encoding='utf-8').read(),`

This required to import the codecs library in the setup.py script as well.

Also, in the distribution that I downloaded (pyfim-0.2.tar.gz)  I had to rename the file `PKG-INFO` to `README.md` for the setup.py to properly work.

**Comment by schlegelp** [comment]
Interesting. Could you perhaps try just this:
```
long_description=open('README.md', encoding="utf-8").read()
```

**Comment by schlegelp** [comment]
Closing this as the issue has been inactive for >1y now.
